### ISSUE TITLE
Request: design description

### ISSUE THREAD

**Issue by grothesque** [fre-hu/mdarray#1]
Thanks for sharing this very interesting library!  I've been trying to understand its inner workings, but this is difficult since some central aspect seem both very clever (in a positive sense), and are not documented at all.  I think that adding a "DESIGN.md" file (even a small one) may greatly increase the usefulness of this project to other people (be it possible contributors or members of the wider numeric Rust community).

For example, would you mind to describe how `Span` works? I note that it is a zero-sized struct, and only `&Span` are passed around.  But what do these actually point to?  And what is the role of `RawSpan`?

Or let's take `Expr` / `Expression`.  I first thought that it's a view with a somewhat badly chosen name, but it seems to be much more than that.  Are types that implement the trait `Expression` "expression templates" in C++ speak?

What is the relation of `Expr` and `Span` and why are both needed?  You write that spans are like Rust slices, but slices are fat pointers, while spans seem to be just pointers that point to... something (that is owned by whom?).

It would be also interesting to have a brief discussion of the design aspects of C++'s mdspan/mdarray that you took over, and those that you didn't/couldn't and the reasons for that.

**Comment by fre-hu** [comment]
Thanks for the suggestion and comments! I have added design notes in the latest commit as a start. The layout types are omitted for now since I'm looking into if they can be improved.

**Comment by fre-hu** [comment]
Yes, right. One way is to do `a.reshape([2, 2])` or so which will change the shape type to have dynamic dimensions.

**Comment by fre-hu** [comment]
I added more conversions for Array to be consistent with normal arrays. It should work now with `&Expr::from(&a)`. Let's see if it is sufficient.

**Comment by fre-hu** [comment]
Yes having Dim parameters per dimension is the way to do it.

I did some testing, and it seems that the missed optimization is due to limitations in alias analysis. I got it to generate packed FMAs by breaking out the inner loop in a separate function. Somehow the Span references must be visible in function arguments for it to optimize. 

If I increase the column length to 64 or make it dynamic, the compiler generates different code paths and checks for aliasing at runtime with the original function.

```
pub fn mul_col<D: Dim>(cj: &mut Span<f64, D>, ak: &Span<f64, D>, bkj: &f64)
{
    for (cij, aik) in cj.expr_mut().zip(ak) {
        *cij = aik.mul_add(*bkj, *cij);
    }
}

pub fn matmul_generic<D0: Dim, D1: Dim, D2: Dim>(
    a: &Span<f64, (D0, D1)>,
    b: &Span<f64, (D1, D2)>,
    c: &mut Span<f64, (D0, D2)>,
) {
    for (mut cj, bj) in c.cols_mut().zip(b.cols()) {
        for (ak, bkj) in a.cols().zip(bj) {
            mul_col(&mut cj, &ak, bkj);
        }
    }
}

pub fn matmul_opt(a: &DSpan<f64, 2>, b: &DSpan<f64, 2>, c: &mut DSpan<f64, 2>) {
    let a = a.reshape((Const::<4>, Dyn(2)));
    let mut c = c.reshape_mut((Const::<4>, Dyn(2)));
    matmul_generic(&a, &b, &mut c);
}
```
