### ISSUE TITLE
Support for dynamic number of dimensions

### ISSUE THREAD

**Issue by grothesque** [fre-hu/mdarray#4]
I reference a discussion from https://github.com/rust-ndarray/ndarray/issues/1272#issuecomment-2325747608:

@fre-hu wrote:
> I think the simplest way is to add dynamic rank as a new shape type and keep the existing layout types. The shape types for static rank are tuples of dimensions (each static or dynamic), and the new type will instead consist of a Box/Vec. The resulting layout mapping will then use Box/Vec for both shape and strides.
> 
> There can be limitations and for some operations like creating array views and permuting dimensions the rank must be static. But yes you can always convert to static rank for calculations.

Please correct me if I'm wrong, but with today's mdarray it is simply not possible to have arrays beyond a certain rank.

Of course there is no way around this with today's Rust given that macros need to be instantiated for each supported number of dimensions.  And also the value of supporting static shapes beyond, say, 10 dimensions, seems marginal.

But for completeness and interfacing with other general array libraries, I think that supporting a fully generic layout would be very valuable.

**Comment by fre-hu** [comment]
Yes, I have a prototype that just needs to be cleaned up.

**Comment by fre-hu** [comment]
Please see the latest commit for dynamic rank support.
